### ISSUE TITLE
Error: Loading chunk 0 failed.

### ISSUE THREAD

**Issue by atefBB** [rluders/oc-theme-angular#6]
After a fresh install of the theme, I followed the instructions in the `REAME` but I encourted the `Error: Loading chunk 0 failed.` after running `ng build --watch` (see picture).
Any ideas to solve the issue?
![devtools](https://user-images.githubusercontent.com/10966925/63378169-87ee7b80-c389-11e9-8ffd-bf8142196ada.png)

**Comment by rluders** [comment]
@atefBB did you configured the `htaccess` as well? It looks exactly like a problem caused by it. Try to follow these instructions:

> Edit your October's `.htaccess` file from your root project and change the line as indicated below.
> 
> From:
> 
> ```
> RewriteCond %{REQUEST_FILENAME} !/themes/.*/(assets|resources)/.*
> ```
> 
> To:
> 
> ```
> RewriteCond %{REQUEST_FILENAME} !/themes/.*/(assets|resources|app)/.*
> ```
> 
> Also, for security reasons, you'll need to add the following lines at the the Block all PHP files, except index section:
> 
> ```
> RewriteRule ^([0-9]+.chunk.js)$ /themes/rluders-angular2/app/$1 [R,L]
> RewriteRule ^(themes/.*/app/index.html) - [F,L,NC]
> ```
> 
> It'll prevent the users to access the `themes/(theme)/app/index.html` and redirect the chunk files. Not that'll be a problem, but it's not nice.

**Comment by atefBB** [comment]
I'll check it. thx.

**Comment by leonardosr** [comment]
This can be solved by changing the file angular/package.json

8: `"build": "ng build --watch --deploy-url /<main folder>/themes/rluders-angular2/app/",`

In my case the command looks like this:

`ng build --watch --deploy-url /october-cms/themes/rluders-angular2/app/`

Then start the application using the following command: npm run-script build

**Comment by rluders** [comment]
Thank you, @leonardosr .

Also, keep in mind that we are working to move the theme to Angular 8. I do not promise that I will be able to review all the pull request this week, 'cause I probably will not have time to do it. But till the end of September we will definitely have an updated version of this theme.

**Comment by atefBB** [comment]
@rluders Good news !
